# Generated by Django 3.1.5 on 2021-01-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelList',
            fields=[
                ('tracking_no', models.CharField(max_length=150)),
                ('postcode', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BookList',
        ),
    ]
