# Generated by Django 3.1.5 on 2021-01-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210112_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverList',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('postcode', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
