# Generated by Django 3.1.5 on 2021-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_driverlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcellist',
            name='compartment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcellist',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
    ]
