# Generated by Django 3.1.5 on 2021-01-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210112_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlist',
            old_name='postcode',
            new_name='max_postcode',
        ),
        migrations.RenameField(
            model_name='driverlist',
            old_name='address',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='driverlist',
            name='name',
        ),
        migrations.AddField(
            model_name='driverlist',
            name='min_postcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
