# Generated by Django 3.1.5 on 2021-01-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210117_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlist',
            name='compartment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
